---
- name: Deploy midnight miner
  hosts: midnight_miners
  become: true

  tasks:
    - name: Ensure miner user exists
      user:
        name: "{{ miner_user }}"
        shell: /bin/bash
        create_home: yes
        system: yes

    - name: Create miner directory
      file:
        path: "{{ miner_dir }}"
        state: directory
        owner: "{{ miner_user }}"
        group: "{{ miner_user }}"
        mode: "0755"

    - name: Fetch install.sh
      get_url:
        url: "{{ install_url }}"
        dest: "{{ miner_dir }}/install.sh"
        mode: "0755"
        owner: "{{ miner_user }}"
        group: "{{ miner_user }}"

    - name: Fetch run.sh
      get_url:
        url: "{{ run_url }}"
        dest: "{{ miner_dir }}/run.sh"
        mode: "0755"
        owner: "{{ miner_user }}"
        group: "{{ miner_user }}"

    - name: Copy .env into miner directory
      copy:
        src: .env                 # relative to the playbook directory
        dest: "{{ miner_dir }}/.env"
        owner: "{{ miner_user }}"
        group: "{{ miner_user }}"
        mode: "0600"              # tighten if it has secrets; use "0644" if not
      notify: Restart midnight-miner

    - name: Set WORKER_THREADS to CPU count
      lineinfile:
        path: "{{ miner_dir }}/.env"
        regexp: '^WORKER_THREADS='
        line: "WORKER_THREADS={{ ansible_processor_vcpus }}"
        owner: "{{ miner_user }}"
        group: "{{ miner_user }}"
        mode: "0600"
      notify: Restart midnight-miner

    - name: Run installer once (idempotent-ish)
      args:
        chdir: "{{ miner_dir }}"
        executable: /bin/bash
      become_user: "{{ miner_user }}"
      shell: |
        set -euo pipefail
        ./install.sh --url "{{ server_url }}"

    - name: Write systemd unit
      copy:
        dest: /etc/systemd/system/midnight-miner.service
        mode: "0644"
        content: |
          [Unit]
          Description=Midnight Miner
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          User={{ miner_user }}
          WorkingDirectory={{ miner_dir }}
          Environment="HOME=/home/{{ miner_user }}"
          EnvironmentFile={{ miner_dir }}/.env
          ExecStart=/bin/bash {{ miner_dir }}/run.sh
          Restart=always
          RestartSec=5
          # Optional: tighten resources a bit
          NoNewPrivileges=true
          ProtectSystem=full

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Enable & start service
      systemd:
        name: midnight-miner
        enabled: true
        state: started

  handlers:
    - name: Restart midnight-miner
      systemd:
        name: midnight-miner
        state: restarted